
import java.time.Duration;
import java.time.Instant;
import java.util.Arrays;
import java.util.Collections;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Lahiruka
 */
public class mainForm extends javax.swing.JFrame {

    /**
     * Creates new form mainForm
     */
    public mainForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane3 = new javax.swing.JScrollPane();
        txtArray = new javax.swing.JTextPane();
        btnGenerateArray = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtSearch = new javax.swing.JTextField();
        txtLinear = new javax.swing.JTextField();
        txtJump = new javax.swing.JTextField();
        txtBinary = new javax.swing.JTextField();
        txtInterpol = new javax.swing.JTextField();
        btnLinear = new javax.swing.JButton();
        btnJump = new javax.swing.JButton();
        btnBinary = new javax.swing.JButton();
        btnInterpol = new javax.swing.JButton();
        lblArr = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtIndexOfInterpol = new javax.swing.JTextField();
        txtIndexOfLinear = new javax.swing.JTextField();
        txtIndexOfJump = new javax.swing.JTextField();
        txtIndexOfBinary = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jScrollPane3.setViewportView(txtArray);

        getContentPane().add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 460, 180));

        btnGenerateArray.setText("Generate Array");
        btnGenerateArray.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGenerateArrayActionPerformed(evt);
            }
        });
        getContentPane().add(btnGenerateArray, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 30, -1, -1));

        jLabel1.setText("Linear Search");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 340, -1, -1));

        jLabel2.setText("Jump Search");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 340, 86, -1));

        jLabel3.setText("Binary Search");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 340, -1, -1));

        jLabel4.setText("Interpolation Search");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 340, -1, -1));
        getContentPane().add(txtSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 170, 80, 30));
        getContentPane().add(txtLinear, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 440, 130, -1));
        getContentPane().add(txtJump, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 440, 130, -1));
        getContentPane().add(txtBinary, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 440, 140, -1));
        getContentPane().add(txtInterpol, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 440, 140, -1));

        btnLinear.setText(">");
        btnLinear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLinearActionPerformed(evt);
            }
        });
        getContentPane().add(btnLinear, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 340, -1, -1));

        btnJump.setText(">");
        btnJump.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnJumpActionPerformed(evt);
            }
        });
        getContentPane().add(btnJump, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 340, -1, -1));

        btnBinary.setText(">");
        btnBinary.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBinaryActionPerformed(evt);
            }
        });
        getContentPane().add(btnBinary, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 340, -1, -1));

        btnInterpol.setText(">");
        btnInterpol.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInterpolActionPerformed(evt);
            }
        });
        getContentPane().add(btnInterpol, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 340, -1, -1));

        lblArr.setText("__");
        getContentPane().add(lblArr, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 210, 30, -1));

        jLabel6.setText("Array generated in :");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 210, -1, -1));

        jLabel5.setText("Index : ");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 380, -1, -1));

        jLabel7.setText("Search Time :");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 440, -1, -1));
        getContentPane().add(txtIndexOfInterpol, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 380, 60, -1));
        getContentPane().add(txtIndexOfLinear, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 380, 60, -1));
        getContentPane().add(txtIndexOfJump, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 380, 60, -1));
        getContentPane().add(txtIndexOfBinary, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 380, 60, -1));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 300, -1, 170));

        jLabel8.setText("Enter any number to search");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 150, 160, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    public void createRandomArray(){
        Integer[] arr = new Integer[10000];
        for(int i= 0; i< arr.length; i++){
            arr[i] =i;
        }
        Collections.shuffle(Arrays.asList(arr));
        txtArray.setText(Arrays.toString(arr));
    }
    
    private void btnGenerateArrayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGenerateArrayActionPerformed
        Instant start = Instant.now();        
        createRandomArray();        
        Instant end = Instant.now();
        Duration timeElapsed = Duration.between(start, end);
        lblArr.setText(String.valueOf(timeElapsed.toMillis()));      
    }//GEN-LAST:event_btnGenerateArrayActionPerformed
    
    public static int linearSearch(int[]array,int number){
        for (int i=0; i<10000; i++){
            if(array[i]==number){
                return i;
            }
        }
        return -1;
    }
    
    public static int jumpSearch(int[] array, int number){
        int jumpStep = (int) Math.sqrt(array.length);
        int prevStep = 0;
        
        while (array[Math.min(jumpStep, array.length)-1]<number){
            prevStep = jumpStep;
            jumpStep += (int)(Math.sqrt(array.length));
                if (prevStep>= array.length)
                    return -1;
        }
        while(array[prevStep]< number){
            prevStep++;
            if(prevStep == Math.min(jumpStep, array.length))
                return -1;
        }
        if (array[prevStep] == number)
            return prevStep;
        return -1;
    }
    
    public static int[] fromString(String string){
        String[] str = string.replace("[", "").replace("]","").split(", ");
        int res[] =new int[str.length];
        for( int i =0 ; i<res.length;i++){
            res[i] = Integer.parseInt(str[i]);
        }
        return res;
    }
    
    private void btnLinearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLinearActionPerformed
        Instant start = Instant.now();
        int num = Integer.parseInt(txtSearch.getText());
        
        //some code starts here
        String s = txtArray.getText();
        int[] arr= fromString(s);
        int i = linearSearch(arr, num);
        txtIndexOfLinear.setText(String.valueOf(i));
        //some code ends here
        
        Instant end = Instant.now();
        Duration timeElapsed = Duration.between(start, end);
        txtLinear.setText(String.valueOf(timeElapsed.toMillis()));
    }//GEN-LAST:event_btnLinearActionPerformed

    private void btnJumpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnJumpActionPerformed
        Instant start = Instant.now();
        int num = Integer.parseInt(txtSearch.getText());
        
        //some code here
        String s = txtArray.getText();
        int[] arr= fromString(s);
        int i = jumpSearch(arr, num);
        txtIndexOfJump.setText(String.valueOf(i));
        //some code here
        
        Instant end = Instant.now();
        Duration timeElapsed = Duration.between(start, end);
        txtJump.setText(String.valueOf(timeElapsed.toMillis()));
    }//GEN-LAST:event_btnJumpActionPerformed

    private void btnBinaryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBinaryActionPerformed
        Instant start = Instant.now();
        int num = Integer.parseInt(txtSearch.getText());
        
        //some code here
        String s = txtArray.getText();
        int[] arr= fromString(s);
        int i = linearSearch(arr, num);
        txtIndexOfBinary.setText(String.valueOf(i));
        //some code here
        
        Instant end = Instant.now();
        Duration timeElapsed = Duration.between(start, end);
        txtBinary.setText(String.valueOf(timeElapsed.toMillis()));
    }//GEN-LAST:event_btnBinaryActionPerformed

    private void btnInterpolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInterpolActionPerformed
        Instant start = Instant.now();
        int num = Integer.parseInt(txtSearch.getText());
        
        //some code here
        String s = txtArray.getText();
        int[] arr= fromString(s);
        int i = linearSearch(arr, num);
        txtIndexOfInterpol.setText(String.valueOf(i));
        //some code here
        
        Instant end = Instant.now();
        Duration timeElapsed = Duration.between(start, end);
        txtInterpol.setText(String.valueOf(timeElapsed.toMillis()));
    }//GEN-LAST:event_btnInterpolActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(mainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(mainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(mainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(mainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new mainForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBinary;
    private javax.swing.JButton btnGenerateArray;
    private javax.swing.JButton btnInterpol;
    private javax.swing.JButton btnJump;
    private javax.swing.JButton btnLinear;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblArr;
    private javax.swing.JTextPane txtArray;
    private javax.swing.JTextField txtBinary;
    private javax.swing.JTextField txtIndexOfBinary;
    private javax.swing.JTextField txtIndexOfInterpol;
    private javax.swing.JTextField txtIndexOfJump;
    private javax.swing.JTextField txtIndexOfLinear;
    private javax.swing.JTextField txtInterpol;
    private javax.swing.JTextField txtJump;
    private javax.swing.JTextField txtLinear;
    private javax.swing.JTextField txtSearch;
    // End of variables declaration//GEN-END:variables
}
