
import java.time.Duration;
import java.time.Instant;
import java.util.Arrays;
import java.util.Collections;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Lahiruka
 */
public class mainForm extends javax.swing.JFrame {

    /**
     * Creates new form mainForm
     */
    public mainForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane3 = new javax.swing.JScrollPane();
        txtArray = new javax.swing.JTextPane();
        btnSearch = new javax.swing.JButton();
        btnGenerateArray = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtSearch = new javax.swing.JTextField();
        txtLinear = new javax.swing.JTextField();
        txtJump = new javax.swing.JTextField();
        txtBinary = new javax.swing.JTextField();
        txtInterpol = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jScrollPane3.setViewportView(txtArray);

        getContentPane().add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, 460, 180));

        btnSearch.setText("Search");
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });
        getContentPane().add(btnSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 280, -1, -1));

        btnGenerateArray.setText("Generate Array");
        btnGenerateArray.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGenerateArrayActionPerformed(evt);
            }
        });
        getContentPane().add(btnGenerateArray, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 80, -1, -1));

        jLabel1.setText("Linear Search");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 340, -1, -1));

        jLabel2.setText("Jump Search");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 340, 86, -1));

        jLabel3.setText("Binary Search");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 340, -1, -1));

        jLabel4.setText("Interpolation Search");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 340, -1, -1));
        getContentPane().add(txtSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 280, 110, 30));
        getContentPane().add(txtLinear, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 370, 130, -1));
        getContentPane().add(txtJump, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 370, 130, -1));
        getContentPane().add(txtBinary, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 370, 140, -1));
        getContentPane().add(txtInterpol, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 370, 140, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        String num = txtSearch.getText();
                
    }//GEN-LAST:event_btnSearchActionPerformed

    private void btnGenerateArrayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGenerateArrayActionPerformed
        Instant start = Instant.now();
        
        Integer[] arr = new Integer[10000];
        for(int i= 0; i< arr.length; i++){
            arr[i] =i;
        }
        Collections.shuffle(Arrays.asList(arr));
        txtArray.setText(Arrays.toString(arr));     
        

        Instant end = Instant.now();
        Duration timeElapsed = Duration.between(start, end);
        txtBinary.setText(String.valueOf(timeElapsed.toMillis()));      
    }//GEN-LAST:event_btnGenerateArrayActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(mainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(mainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(mainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(mainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new mainForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGenerateArray;
    private javax.swing.JButton btnSearch;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextPane txtArray;
    private javax.swing.JTextField txtBinary;
    private javax.swing.JTextField txtInterpol;
    private javax.swing.JTextField txtJump;
    private javax.swing.JTextField txtLinear;
    private javax.swing.JTextField txtSearch;
    // End of variables declaration//GEN-END:variables
}
